/geometry/source ../Al.tg
/physics_lists/select QGSP_BERT
/run/initialize 

/gps/particle e-
/gps/energy 0.2558 eV
/gps/pos/centre -50 0 0 cm
/gps/ang/type iso
/gps/ang/minphi 140 deg
/gps/ang/maxphi 220 deg
/gps/ang/mintheta 55 deg
/gps/ang/maxtheta 125 deg

/vis/open VRML2FILE
/vis/drawVolume
/vis/viewer/flush

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100000

/analysis/setFileName gears.csv

/run/verbose 2
/run/beamOn 10000